language: python
sudo: false
cache:
- apt
- pip
python:
- '2.7'
- '3.4'
- '3.5'
env:
  matrix:
  - DJANGO="Django<1.9,>=1.8"
  - DJANGO="Django<1.10,>=1.9"
  - DJANGO="Django<1.11,>=1.10"
  - DJANGO="-e git+https://github.com/django/django.git@master#egg=Django"
matrix:
  fast_finish: true
  allow_failures:
  - env: DJANGO="-e git+https://github.com/django/django.git@master#egg=Django"
install:
- pip install --upgrade pip
- pip install -r requirements_dev.txt
- pip install $DJANGO
- pip install coveralls
script:
- flake8 --jobs=2 .
- coverage run --source=abstract_relations -m py.test
after_success:
- coveralls
deploy:
  - provider: pypi
    distributions: sdist
    server: https://testpypi.python.org/pypi
    user: molski
    password:
      secure: UqnqXntG0i1U2i8YYOjaZnn8dltFbNPCiKECPwPLmSB/a8tqVfvxuRPuuMD1tkurRRrvCf37u3xmi+wFkOv1D3AKxB3C43jbiUGkPXH0uvQm2fGM47RtSp6NlUT/0X+vsfnDMrKvjwh9lIxUrp1IYgm1TEnKRrCae/ne2fQBNsaIPb+RS2ecssJ7ZAIRO8Y8Q8Kw9a25Yg6mQ9W0a2VZ7Dl3ewWjlthCECB/vbOibauWBpQECoXIrENogVysG+Nr0q74V46e+sY4ufD/eKBE6rNNQKiMoG53Z2JEBCeQaHkVAaDEeKXnF1FqSt2RAxCe8WZ64xaWbjpo2MptBOXO4u8g2pR51O+DqeQCAW2l+V8p2shY3px1EWVG+LQfBHZhoOwveqlwS5WuOZXRbvF3aMh4g3/R3tTe8FqyyvlRDTRuBsm08mllYdbXwYa55e9RZiG8CQh3gPBULG0tIxnC+amZT2sC3R2Bx6i6bcS9fNa9yvPTHI5+g3evwMboNw3mZQAW+b/UpE+dkwa94kiXxYnKI6Dd1ElHZvmtB/xI09S7YgFNvkafqf2QRj1/GquxkOGK2Z9dPTy7Fybw/vzjMX1cQe7GgPbPq/5Jyn5md3bTWJ/pB8A2BFaPYPQbnCpFmYIKgwhDX1vwbGoJL0HJESxvpkN6dTXG4xBkcq5ggq4=
    on:
      branch: master
      tags: false
      condition: $TRAVIS_PYTHON_VERSION = "3.5"
